config/routes.rb
Bridgeport::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/signin' => 'devise/sessions#new'
    get '/signout' => 'devise/sessions#destroy'
  end

  mount Mercury::Engine => '/'
  
  namespace :admin do
    resources :pages, :except => 'edit' do
      post :sort, :on => :collection
    end
    resources :users
    match '' => 'pages#index'
  end
  
  resources :pages, :only => [:index, :show]
  
  namespace :mercury do
    resources :images
  end
  
  get '/admin/pages/*id', :to => 'admin/pages#show'
  put '/admin/pages/*id', :to => 'admin/pages#update'
  match '*id', :to => 'pages#show'
  
  
  root :to => 'pages#index'

end

app/views/admin/pages/_page_item.html.erb
<div class="page_item">
  <div class="title">
    <strong><%= page.title %></strong>
  </div>
  <div class="ops">
    <%= link_to 'View', admin_page_path(page) %>
    | <%= link_to 'Edit', "/editor" + admin_page_path(page) %>
    | <%= link_to 'Delete', admin_page_path(page), :method => 'delete', :confirm => 'Are you sure you want to delete this page?' %>
  </div>
</div>

app/views/admin/pages/index.html.erb
<section id="admin_home" class="container">
  <div class="row">
    <h2>Site Structure</h2>
  </div>
  <div class="row">
    <div class="eight columns">
      
      <ol class="page_sorter" data-update-url="<%= sort_admin_pages_path %>">
        <%= nested_pages(@pages) %>
      </ol>
      
    </div>
    <div class="four columns">
      <p><%= link_to 'New', "/editor" + new_admin_page_path %></p>
    </div>
  </div>
</section>

app/views/admin/pages/new.html.erb
<div class="container">
  <section id="new_page">
    <div class="row">
      <header class="twelve columns">
        <h1 id="title" class="mercury-region" data-mercury="simple">New Page Title</h1>
      </header>
    </div>
    <div class="row">
      <div class="primary eight columns">
        <div id="region_1" class="mercury-region" data-mercury="full" data-position="1" data-width="eight" data-label="primary">
          <p>Replace this text.</p>
          <p>Vestibulum id ligula porta felis euismod semper. Etiam porta sem malesuada magna mollis euismod. Donec ullamcorper nulla non metus auctor fringilla. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>

          <p>Maecenas faucibus mollis interdum. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Maecenas sed diam eget risus varius blandit sit amet non magna. Maecenas sed diam eget risus varius blandit sit amet non magna. Nullam quis risus eget urna mollis ornare vel eu leo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.</p>

          <p>Donec ullamcorper nulla non metus auctor fringilla. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Donec sed odio dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas faucibus mollis interdum. Donec id elit non mi porta gravida at eget metus. Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
        </div>
      </div>
      <div class="sidebar four columns">
        <div id="region_2" class="mercury-region" data-mercury="full" data-position="2" data-width="four" data-label="sidebar">
          <p>Replace this text.</p>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/admin/pages/show.html.erb
<div class="container">
  <section id="<%= @page.slug %>">
    <div class="row">
      <header class="twelve columns">
        <h1 id="title" class="mercury-region" data-mercury="simple"><%= @page.title %></h1>
      </header>
    </div>
    <% if @page.regions.any? %>
    <div id="regions" class="regions row">
      <% @page.sorted_regions.each_with_index do |r, i| %>
      <div class="<%= "#{r.label} #{r.width}" %> columns">
        <div id="<%= r.id %>" class="mercury-region" data-mercury="full" data-position="<%= i+1 %>" data-width="<%= r.width %>" data-label="<%= r.label %>">
          <% if edit_mode? %>
            <%= raw r.body %>
          <% else %>
            <%= raw r.body_with_links %>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>
    <% end %>
    

    <div id="region_template" class="two columns" style="display:none">
      <div id="new_region">
        <p>Text from template</p>
      </div>
    </div>
    
  </section>
</div>