config/routes.rb
Bridgeport::Application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/signin' => 'devise/sessions#new'
    get '/signout' => 'devise/sessions#destroy'
  end

  mount Mercury::Engine => '/'
  
  namespace :admin do
    resources :pages, :except => 'edit' do
      post :sort, :on => :collection
    end
    resources :users
    match '' => 'pages#index'
  end
  
  resources :pages, :only => [:index, :show]
  
  namespace :mercury do
    resources :images
  end
  
  get '/admin/pages/*id', :to => 'admin/pages#show'
  put '/admin/pages/*id', :to => 'admin/pages#update'
  match '*id', :to => 'pages#show'
  
  
  root :to => 'pages#index'

end

app/views/layouts/admin.html.erb
<% content_for :admin do %>
  <div id="admin">
    <div class="container">
      <div class="row">
        <div class="two columns">
          <h4>Admin</h4>
        </div>
        <div class="eight columns">
          <ul class="menu">
            <li><%= link_to "All pages", admin_pages_path %></li>
            <li><%= link_to "Edit Page", "/editor" + request.path if action_name == 'show' %></li>
          </ul>
        </div>
        <div id="account" class="two columns">
          <% if user_signed_in? %>
          <%= current_user.email %><br>
          <%= link_to 'Sign Out', signout_path %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>
<%= render :template => 'layouts/application' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <title>Bridgeport School</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">

  <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->
  

  <%= stylesheet_link_tag "application", :media => "all" %>
  
  <% if user_signed_in? %>
    <%= javascript_include_tag "admin" %>
  <% else %>
    <%= javascript_include_tag "application" %>
  <% end %>
  <%= csrf_meta_tags %>
</head>

<body<%= edit_mode_class %>>
  <%= content_for :admin %>
<div id="page">
  <header>
    <div class="container">
      
      <hgroup>
        <h1>Bridgeport School</h1>
        <h2>All Students Succeed</h2>
      </hgroup>
      <nav>
        <ul class="six">
          <% @roots.each do |page| %>
          <li><%= link_to page.title, switch_path(page, user_signed_in?)%></li>
          <% end %>
        </ul>
      </nav>
      
    </div>
  </header>
  <div id="main">
    <% unless notice.nil? && alert.nil? %>
    <div id="messages">
      <div class="container">
        <div class="row">
          <% unless notice.nil? %>
          <div class="notice">
            <%= notice %>
          </div>
          <% end %>
          <% unless alert.nil? %>
          <div class="alert">
            <%= alert %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
    
    <%= yield %>
    
  </div>
  <footer>
    
  </footer>
</div>


</body>
</html>

app/views/layouts/empty.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <title>School CMS</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width">

  <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->
  

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <% # javascript_include_tag "admin" %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <div id="page">
    
    <div id="main">
      <%= yield %>
    </div>

  </div>
  
  <footer>

  </footer>

</body>
</html>

app/views/layouts/mercury.html.erb
<% # binding.pry %>
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, maximum-scale=1.0, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <title>Mercury Editor</title>
    <%= stylesheet_link_tag    'mercury', 'mercury_overrides' %>
    <%= javascript_include_tag 'mercury_all' %>
  </head>
  <body>
    <script type="text/javascript">
      var newpage = /new$/.test(window.location.pathname);
      var saveUrl;
      var options = { saveStyle: 'form', saveMethod: 'PUT', visible: null };
      if(newpage){
        saveUrl = "/admin/pages";
        options.saveMethod = 'POST';
      }else{
        saveUrl = null;
        
      }
      

      //<!-- Mix in any configurations provided through Rails.application.config.mercury_config -->
      <% if Rails.application.config.respond_to?(:mercury_config) %>
        jQuery.extend(Mercury.config, <%= Rails.application.config.mercury_config.to_json.html_safe %>);
      <% end -%>

      //<!-- Mix in any options for PageEditor provided through Rails.application.config.mercury_page_editor_config -->
      <% if Rails.application.config.respond_to?(:mercury_page_editor_config) %>
        jQuery.extend(options, <%= Rails.application.config.mercury_page_editor_config.to_json.html_safe %>);
      <% end -%>

      //<!-- Instantiate the PageEditor -->
      new Mercury.PageEditor(saveUrl, options);
    </script>
  </body>
</html>